directories:
  output: release
  buildResources: build
appId: com.trpg.module-notes
productName: TRPG模组笔记
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
win:
  signAndEditExecutable: false
  icon: build/icon.ico
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 31.7.7
